# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 06:22
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_auto_20180131_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=django_extensions.db.fields.RandomCharField(blank=True, db_index=True, editable=False, include_alpha=False, length=12, unique=True),
        ),
    ]
