# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 13:22
from __future__ import unicode_literals

import caching.base
from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0004_author_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.RandomCharField(blank=True, db_index=True, editable=False, include_alpha=False, length=12, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('bio', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('web_site', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('avatar', models.URLField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(default='', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organization',
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('nickname', models.CharField(blank=True, max_length=128)),
                ('bio', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('web_site', models.URLField(blank=True, max_length=255, null=True)),
                ('avatar', models.URLField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(default='', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'people',
                'verbose_name_plural': 'people',
                'ordering': ('-created_at',),
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='author',
            name='dapp',
        ),
        migrations.RemoveField(
            model_name='authorprofile',
            name='author',
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name': 'repository', 'verbose_name_plural': 'repositories'},
        ),
        migrations.RemoveField(
            model_name='repository',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='repository',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='identified_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='repository',
            name='author',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='repository',
            name='readme',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='AuthorProfile',
        ),
    ]
