# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 02:54
from __future__ import unicode_literals

import caching.base
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0005_auto_20180206_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch', models.PositiveIntegerField(default=0)),
                ('star', models.PositiveIntegerField(default=0)),
                ('fork', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('repos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='github.Repository')),
            ],
            options={
                'ordering': ('-date',),
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
    ]
