# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 02:52
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('github', '0006_repositorystate'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
