# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0010_auto_20180215_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
