# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0011_repository_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ('updated_at',), 'verbose_name': 'repository', 'verbose_name_plural': 'repositories'},
        ),
    ]
