# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0012_auto_20180215_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=128)),
                ('commit_datetime', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('repos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit', to='github.Repository')),
            ],
        ),
    ]
