# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0013_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
