# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0014_organization_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.IntegerField(choices=[(0, 'user'), (1, 'organization')], default=0),
        ),
        migrations.AddField(
            model_name='people',
            name='company',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='people',
            name='updated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
