# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0017_people_html_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='web_site',
            new_name='blog',
        ),
    ]
