# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0018_auto_20180620_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='nickname',
            new_name='login',
        ),
    ]
