# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0019_auto_20180621_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ('-created_at',), 'verbose_name': 'users', 'verbose_name_plural': 'user'},
        ),
        migrations.AddField(
            model_name='repository',
            name='homepage',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='language',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='pushed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
