# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0020_auto_20180622_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='html_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
