# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0021_repository_html_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
