# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0023_auto_20180622_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ('-updated_at',), 'verbose_name': 'repository', 'verbose_name_plural': 'repositories'},
        ),
    ]
