# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0024_auto_20180622_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='login',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
