# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0025_auto_20180625_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
