# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0026_auto_20180625_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='forks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='stargazers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='watchers_count',
            field=models.IntegerField(default=0),
        ),
    ]
