# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0027_auto_20180625_1606'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=set([('author', 'name')]),
        ),
    ]
