# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 09:14
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0028_auto_20180625_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
