# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0029_auto_20180625_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='branch',
            field=models.CharField(default='master', max_length=255),
        ),
    ]
