# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0030_commit_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='commit_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
