# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0032_auto_20180625_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
