# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0034_people_alive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='pushed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
