BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBB

BBBBB BBBBBXXXXXXXX X XXXXXXXXXXXXBBBBBBBB BBBBB

BBBBB BBBBBBBBB
    BBBBBBBB BBB
        XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    BBBBBBBBBBB
BBBBBBBB


BBBBB BBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB

 BBBBB BBBBBBBBBBBBBBBB
     BBBBBBBB BB
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXX
     BBBBBBBBBBB
 BBBBBBBB BBBBBBBBBBBBBBBB
