BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBB

BBBBB BBBBBXX X XXXXXXXXBBBBBBBB

BBBBB BBBBBBB

    XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XX
        XXXX XXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXX
                BB BBBBBBBBBBB
                    XXX gettext(u"Your username and password didn't match. Please try again.") XXXX
                BBBBB

                XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBXXBBBBBBBBBB
                    FFFFF
                    XXXX XXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Log in') XXXXXXXXX
                    XXXXXX
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB