BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBB

BBBBB BBBBBXXXXX X XXXXXXXXXXXXBBBBBBBB


BBBBB BBBBBBB
    XXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
                BBB BBB BB BBBBBBBBBBB
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBB
                BBBBBB
            XXXXXX

            BBBBBBBBBBBBBBBB BBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
    XXXXXXXXXX
BBBBBBBB