# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0007_auto_20180118_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='logo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.URLField(max_length=255),
        ),
    ]
