# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0009_auto_20180119_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='dapp',
            name='etherian',
            field=models.CharField(default='', max_length=255),
        ),
    ]
