# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0011_dapp_founder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dapp',
            name='vc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
