# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 12:50
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0014_auto_20180119_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='dapp',
            name='slug',
            field=django_extensions.db.fields.RandomCharField(blank=True, db_index=True, editable=False, include_alpha=False, length=12, unique=True),
        ),
    ]
