# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0017_auto_20180130_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='github',
            name='readme',
        ),
        migrations.AddField(
            model_name='github',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='github',
            name='blog',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='github',
            name='html_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
