# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0019_github_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='github',
            name='mail',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
