# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0020_github_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='github',
            old_name='mail',
            new_name='email',
        ),
    ]
