# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0021_auto_20180622_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='github',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
