# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0023_github_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dapp',
            name='symbol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
