# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0024_auto_20180624_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dapp',
            options={'verbose_name': 'Decentralised Applications', 'verbose_name_plural': 'Decentralised Applications'},
        ),
    ]
