# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0025_auto_20180704_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='dapp',
            name='bio',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
