# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0004_auto_20180118_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'verbose_name': 'Email Address',
            },
        ),
        migrations.AddField(
            model_name='dapp',
            name='faq',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='social',
            name='google_plus',
            field=models.URLField(default='', max_length=255, verbose_name='Google+'),
        ),
        migrations.AddField(
            model_name='social',
            name='kakao',
            field=models.URLField(default='', max_length=255, verbose_name='Kakao'),
        ),
        migrations.AlterField(
            model_name='social',
            name='youtube',
            field=models.URLField(default='', max_length=255, verbose_name='Youtube'),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='dapp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='dapps.DApp'),
        ),
    ]
