# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0006_auto_20180118_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dapp',
            name='last_update',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dapp',
            name='submitted',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
