# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0008_auto_20180118_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='dapp',
        ),
        migrations.AddField(
            model_name='site',
            name='logo',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
