# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0013_auto_20180119_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='whitepaper',
            field=models.URLField(max_length=1024),
        ),
    ]
