# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0015_dapp_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='dapp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='dapps.DApp'),
        ),
    ]
