XXXX XXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX
         X 
    XXXX
    XXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX
                XXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX
                XXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX
                XXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX