# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0008_auto_20180215_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorystats',
            name='date',
            field=models.DateField(auto_created=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='repositorystats',
            name='repos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='github.Repository'),
        ),
    ]
