BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBB

BBBBB BBBBBBBBBBBBB

BBBBB BBBBBBB
    XXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
            BBB BBB BB BBBBBBBBBBB
                XXXX XXXXXXXXXXXXX XXXXXX
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBB
                XXXXXX
            BBBBBB
            XXXXXX

            BBBBBBBBBBBBBBBB BBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
    XXXXXXXXXX
BBBBBBBB